# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TigerTrade Redux
# email: evan.wildenhain@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  TigerTrade is a platform that is widely-used (mostly by graduate students) for buying and
  selling goods. It last saw active development by Rodrigo Menezes ‘13, and is aging by the
  day. The goal of our project is to revamp TigerApps by reimplementing it on a modern
  stack with new features that would make it sufficiently appealing for undergraduates
  to use.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
# github_username:  

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
